name: Docker Image CI

on:
  push:
    # branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag flb-tg:${{ github.ref_name }}

      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: docker/login-action@v1
        with:
          registry: suapapa
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASS }}

      - name: Set up QEMU
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Try to Build the Docker image to Verify
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: |
            suapapa/flb-tg:dev
          build-args: |
            VERSION=dev

      - name: Release the Docker image to DockerHub
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            suapapa/flb-tg:${{ github.ref_name }}
            suapapa/flb-tg:latest
          build-args: |
            VERSION=${{ github._ref_name }}
